"""Add gamification fields to User model

Revision ID: 52af168a4dc0
Revises: 
Create Date: 2025-11-17 20:16:55.479975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52af168a4dc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('streak_days', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_activity_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('achievements', sa.JSON(), nullable=True, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('achievements')
        batch_op.drop_column('last_activity_date')
        batch_op.drop_column('streak_days')
        batch_op.drop_column('level')
        batch_op.drop_column('xp')

    # ### end Alembic commands ###
